# Generated by Django 5.2.1 on 2025-05-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
